SELECT
--FROM ORDERS
    O.*
--FROM CUSTOMER
    , C.*
--FROM PRODUCT
    , P.*
    , (O.ORDER_SELLING_PRICE - O.ORDER_COST_PRICE) AS ORDER_PROFIT
FROM
    {{ ref('ORDERS') }} AS O
LEFT JOIN
    {{ ref('CUSTOMER') }} AS C
ON 
    C.CUSTOMERID = O.CUSTOMER_ID
LEFT JOIN
    {{ ref('PRODUCT') }} AS P
ON
    P.PRODUCTID = O.PRODUCT_ID